"""refactor: removed fileunit

Revision ID: 1c474b8bcdba
Revises: 9013fff7a55b
Create Date: 2025-06-04 13:50:00.526152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c474b8bcdba'
down_revision: Union[str, None] = '9013fff7a55b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('unit', postgresql.ENUM('KiloBytes', 'MegaBytes', name='filesize'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
