"""added document name to document model

Revision ID: 593fb8492896
Revises: e0666a545b14
Create Date: 2025-04-21 23:33:49.370392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '593fb8492896'
down_revision: Union[str, None] = 'e0666a545b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('users', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('users_telegram_user_id_key', 'users', type_='unique')
    op.drop_constraint('users_telegram_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_telegram_username_key', 'users', ['telegram_username'])
    op.create_unique_constraint('users_telegram_user_id_key', 'users', ['telegram_user_id'])
    op.alter_column('users', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('documents', 'document_name')
    # ### end Alembic commands ###
