"""refactor: telegram username optional

Revision ID: 9013fff7a55b
Revises: 4963bd10d93b
Create Date: 2025-05-28 09:29:31.197100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '9013fff7a55b'
down_revision: Union[str, None] = '4963bd10d93b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
