"""added document forignkey to document embedding

Revision ID: aeecb3d15b55
Revises: 4918834a52c1
Create Date: 2025-04-11 13:05:51.343961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'aeecb3d15b55'
down_revision: Union[str, None] = '4918834a52c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_embeddings', sa.Column('document_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'document_embeddings', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_embeddings', type_='foreignkey')
    op.drop_column('document_embeddings', 'document_id')
    # ### end Alembic commands ###
