"""empty message

Revision ID: c86a976b68c4
Revises: d6c66ffb0d52
Create Date: 2025-05-05 13:17:45.114351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'c86a976b68c4'
down_revision: Union[str, None] = 'd6c66ffb0d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_instance', sa.Integer(), nullable=False))
    op.drop_column('users', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'chat_instance')
    # ### end Alembic commands ###
